env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: "xterm-256color"
font:
  normal:
    family: 3270 Nerd Font
  size: 14

# Cursor configuration
cursor:
  style: block # Sets the style of the cursor. Options are: Block, Underline, or Beam.
  unfocused_hollow: false  # Determines whether the cursor is hollow when the window is unfocused. Options are: true or false.

colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    # background: '#282828'
    background: '#1d2021'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
