window:
  option_as_alt: OnlyLeft

shell:
  program: /bin/tmux

  # Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    family: 3270NerdFont
    style: Regular

  # Bold font face
  bold:
    family: HackNerdFont
    style: Bold

  # Italic font face
  italic:
    family: HackNerdFont
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

  # Point size
  size: 10.0

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'


