# https://alacritty.org/config-alacritty.html
[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[cursor]
style = "block"
unfocused_hollow = false

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.7"

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[font]
size = 18

[font.normal]
family = "3270 Nerd Font"

[window]
decorations = "None"
option_as_alt = "Both"
